# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Source Options
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to use free, open source options for accomplishing programming and data
  science tasks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opensourceoptions.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  opensourceoptions

# Build settings
markdown: kramdown
#theme: minima
collections:
    python:
        output: true
        title: Python
        name: python
    r:
        output: true
        title: R
        name: r
    cpp:
        output: true
        title: C++
        name: cpp
    gis:
        output: true
        title: GIS
        name: gis
    
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
